// <auto-generated />
using System;
using BackendCoursFlow.Donnees;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace coursFlow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdFiliere");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Disponibilite", b =>
                {
                    b.Property<int>("IdDispo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispo"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("IdProf")
                        .HasColumnType("integer");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IdDispo");

                    b.HasIndex("IdProf");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFiliere"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdFiliere");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<string>("AnneeUniversitaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ClasseIdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("Duree")
                        .HasColumnType("integer");

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesseurId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer");

                    b.Property<int?>("SalleId")
                        .HasColumnType("integer");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("integer");

                    b.HasKey("IdCours");

                    b.HasIndex("ClasseIdClasse");

                    b.HasIndex("MatiereId");

                    b.HasIndex("ProfesseurId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("SalleId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEmploi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmploi"));

                    b.Property<int>("ClasseId")
                        .HasColumnType("integer");

                    b.Property<int>("CoursId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer");

                    b.HasKey("IdEmploi");

                    b.HasIndex("ClasseId");

                    b.HasIndex("CoursId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer");

                    b.Property<int>("VolumeHoraireGlobal")
                        .HasColumnType("integer");

                    b.HasKey("IdMatiere");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ResponsableId");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.PreRequis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatiereId")
                        .HasColumnType("integer");

                    b.Property<int>("MatierePrerequisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.HasIndex("MatierePrerequisId");

                    b.ToTable("PreRequis");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Salles.DisponibiliteSalle", b =>
                {
                    b.Property<int>("IdDispoSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispoSalle"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IdDispoSalle");

                    b.HasIndex("SalleId");

                    b.ToTable("DisponibilitesSalles");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Salles.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalle"));

                    b.Property<string>("Batiment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdmin"));

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("IdAdmin");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Etudiant", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<int>("ClasseIdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("FiliereIdFiliere")
                        .HasColumnType("integer");

                    b.Property<string>("Groupe")
                        .HasColumnType("text");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("integer");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasIndex("ClasseIdClasse");

                    b.HasIndex("FiliereIdFiliere");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Utilisateurs", t =>
                        {
                            t.Property("UtilisateurId")
                                .HasColumnName("Etudiant_UtilisateurId");
                        });

                    b.HasDiscriminator().HasValue("Etudiant");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Professeur", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProf")
                        .HasColumnType("integer");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Utilisateurs", t =>
                        {
                            t.Property("UtilisateurId")
                                .HasColumnName("Professeur_UtilisateurId");
                        });

                    b.HasDiscriminator().HasValue("Professeur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Responsable", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Responsable");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Classe", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Filiere", "Filiere")
                        .WithMany("Classes")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Disponibilite", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Professeur", "Professeur")
                        .WithMany("Disponibilites")
                        .HasForeignKey("IdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Cours", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Classe", null)
                        .WithMany("Cours")
                        .HasForeignKey("ClasseIdClasse");

                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Matiere", "Matiere")
                        .WithMany("Cours")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Professeur", "Professeur")
                        .WithMany("Cours")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Responsable", null)
                        .WithMany("Cours")
                        .HasForeignKey("ResponsableId");

                    b.HasOne("BackendCoursFlow.Models.Salles.Salle", "Salle")
                        .WithMany("Cours")
                        .HasForeignKey("SalleId");

                    b.Navigation("Matiere");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.EmploiDuTemps", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Cours", "Cours")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Responsable", null)
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("ResponsableId");

                    b.Navigation("Classe");

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Matiere", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Responsable", null)
                        .WithMany("Matieres")
                        .HasForeignKey("ResponsableId");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.PreRequis", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Matiere", "Matiere")
                        .WithMany("PreRequis")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Matiere", "MatierePrerequis")
                        .WithMany("PreRequisPour")
                        .HasForeignKey("MatierePrerequisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("MatierePrerequis");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Salles.DisponibiliteSalle", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Salles.Salle", "Salle")
                        .WithMany("Disponibilites")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Admin", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithOne("Admin")
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Admin", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Etudiant", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseIdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Filiere", "Filiere")
                        .WithMany("Etudiants")
                        .HasForeignKey("FiliereIdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithOne("Etudiant")
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Etudiant", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Filiere");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Professeur", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithOne("Professeur")
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Professeur", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Responsable", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithOne("Responsable")
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Responsable", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Classe", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Filiere", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Cours", b =>
                {
                    b.Navigation("EmploisDuTemps");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Matiere", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("PreRequis");

                    b.Navigation("PreRequisPour");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Salles.Salle", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Disponibilites");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Utilisateur", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Etudiant");

                    b.Navigation("Professeur");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Professeur", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Disponibilites");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Responsable", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Matieres");
                });
#pragma warning restore 612, 618
        }
    }
}
